name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - uses: actions/checkout@v4

    # 2️⃣ Build Docker images
    - name: Build Docker images
      run: docker compose build --no-cache

    # 3️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 4️⃣ Push images
    - name: Push Docker images
      run: docker compose push

    # 5️⃣ Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ vars.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd ~/app
          docker-compose down
          docker image prune -a -f
          docker-compose pull
          docker-compose run --rm web python manage.py migrate
          docker-compose run --rm web python manage.py collectstatic --noinput
          docker-compose up -d


    # 6️⃣ Health check
    - name: Health check
      run: |
        sleep 15
        curl -f http://${{ secrets.SERVER_IP }}:8000 || exit 1
